-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

-- Add config folder to watchlist for config reloads.
local wezterm = require 'wezterm';
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)

local w = require('wezterm')
local config = w.config_builder()
local w = require('wezterm')

config.enable_tab_bar = false
config.color_scheme = 'GruvboxDark'

config.window_padding = {
	left = 1,
	right = 1,
	top = 0,
	bottom = 0,
}

config.font = wezterm.font({
	family = 'ComicShannsMono Nerd Font Mono',
})

return config
		
