#! /bin/sh
/home/maks/.screenlayout/main_pc.sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O VGA-0 VGA1
bspc monitor 'VGA-0' -d '1' '2' '3' '4' '5'
bspc monitor 'VGA-1-1' -d '6' '7' '8' '9' '10'

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a Spotify desktop='^9'
bspc rule -a Pavucontrol state='floating'

/home/maks/shit/ss.sh &
feh --bg-fill ~/.config/wallpapers.webp &
/home/maks/.config/polybar/polybar.sh
setxkbmap -layout us,ru -option grp:win_space_toggle
